export const professions =[
    { label: 'Academic librarian' },
    { label: 'Accountant' },
    { label: 'Accounting technician' },
    { label: 'Actuary' },
    { label: 'Adult nurse' },
    { label: 'Advertising account executive' },
    { label: 'Advertising account planner' },
    { label: 'Advertising copywriter' },
    { label: 'Advice worker' },
    { label: 'Advocate (Scotland)' },
    { label: 'Aeronautical engineer' },
    { label: 'Agricultural consultant' },
    { label: 'Agricultural manager' },
    { label: 'Aid worker/humanitarian worker' },
    { label: 'Air traffic controller' },
    { label: 'Airline cabin crew' },
    { label: 'Amenity horticulturist' },
    { label: 'Analytical chemist' },
    { label: 'Animal nutritionist' },
    { label: 'Animator' },
    { label: 'Archaeologist' },
    { label: 'Architect' },
    { label: 'Architectural technologist' },
    { label: 'Archivist' },
    { label: 'Armed forces officer' },
    { label: 'Aromatherapist' },
    { label: 'Art therapist' },
    { label: 'Arts administrator' },
    { label: 'Auditor' },
    { label: 'Automotive engineer' },
    { label: 'Barrister' },
    { label: 'Barrister’s clerk' },
    { label: 'Bilingual secretary' },
    { label: 'Biomedical engineer' },
    { label: 'Biomedical scientist' },
    { label: 'Biotechnologist' },
    { label: 'Brand manager' },
    { label: 'Broadcasting presenter' },
    { label: 'Building control officer/surveyor' },
    { label: 'Building services engineer' },
    { label: 'Building surveyor' },
    { label: 'Camera operator' },
    { label: 'Careers adviser (higher education)' },
    { label: 'Careers adviser' },
    { label: 'Careers consultant' },
    { label: 'Cartographer' },
    { label: 'Catering manager' },
    { label: 'Charities administrator' },
    { label: 'Charities fundraiser' },
    { label: 'Chemical (process) engineer' },
    { label: 'Child psychotherapist' },
    { label: 'Childrens nurse' },
    { label: 'Chiropractor' },
    { label: 'Civil engineer' },
    { label: 'Civil Service administrator' },
    { label: 'Clinical biochemist' },
    { label: 'Clinical cytogeneticist' },
    { label: 'Clinical microbiologist' },
    { label: 'Clinical molecular geneticist' },
    { label: 'Clinical research associate' },
    { label: 'Clinical scientist - tissue typing' },
    { label: 'Clothing and textile technologist' },
    { label: 'Colour technologist' },
    { label: 'Commercial horticulturist' },
    { label: 'Commercial/residential/rural surveyor' },
    { label: 'Commissioning editor' },
    { label: 'Commissioning engineer' },
    { label: 'Commodity broker' },
    { label: 'Communications engineer' },
    { label: 'Community arts worker' },
    { label: 'Community education officer' },
    { label: 'Community worker' },
    { label: 'Company secretary' },
    { label: 'Computer sales support' },
    { label: 'Computer scientist' },
    { label: 'Conference organiser' },
    { label: 'Consultant' },
    { label: 'Consumer rights adviser' },
    { label: 'Control and instrumentation engineer' },
    { label: 'Corporate banker' },
    { label: 'Corporate treasurer' },
    { label: 'Counsellor' },
    { label: 'Courier/tour guide' },
    { label: 'Court reporter/verbatim reporter' },
    { label: 'Credit analyst' },
    { label: 'Crown Prosecution Service lawyer' },
    { label: 'Crystallographer' },
    { label: 'Curator' },
    { label: 'Customs officer' },
    { label: 'Cyber security specialist' },
    { label: 'Dance movement therapist' },
    { label: 'Data analyst' },
    { label: 'Data scientist' },
    { label: 'Data visualisation analyst' },
    { label: 'Database administrator' },
    { label: 'Debt/finance adviser' },
    { label: 'Dental hygienist' },
    { label: 'Dentist' },
    { label: 'Design engineer' },
    { label: 'Dietitian' },
    { label: 'Diplomatic service' },
    { label: 'Doctor (general practitioner }, GP)' },
    { label: 'Doctor (hospital)' },
    { label: 'Dramatherapist' },
    { label: 'Economist' },
    { label: 'Editorial assistant' },
    { label: 'Education administrator' },
    { label: 'Electrical engineer' },
    { label: 'Electronics engineer' },
    { label: 'Employment advice worker' },
    { label: 'Energy conservation officer' },
    { label: 'Engineering geologist' },
    { label: 'Environmental education officer' },
    { label: 'Environmental health officer' },
    { label: 'Environmental manager' },
    { label: 'Environmental scientist' },
    { label: 'Equal opportunities officer' },
    { label: 'Equality and diversity officer' },
    { label: 'Ergonomist' },
    { label: 'Estate agent' },
    { label: 'European Commission administrators' },
    { label: 'Exhibition display designer' },
    { label: 'Exhibition organiser' },
    { label: 'Exploration geologist' },
    { label: 'Facilities manager' },
    { label: 'Field trials officer' },
    { label: 'Financial manager' },
    { label: 'Firefighter' },
    { label: 'Fisheries officer' },
    { label: 'Fitness centre manager' },
    { label: 'Food scientist' },
    { label: 'Food technologist' },
    { label: 'Forensic scientist' },
    { label: 'Geneticist' },
    { label: 'Geographical information systems manager' },
    { label: 'Geomatics/land surveyor' },
    { label: 'Government lawyer' },
    { label: 'Government research officer' },
    { label: 'Graphic designer' },
    { label: 'Health and safety adviser' },
    { label: 'Health and safety inspector' },
    { label: 'Health promotion specialist' },
    { label: 'Health service manager' },
    { label: 'Health visitor' },
    { label: 'Herbalist' },
    { label: 'Heritage manager' },
    { label: 'Higher education administrator' },
    { label: 'Higher education advice worker' },
    { label: 'Homeless worker' },
    { label: 'Horticultural consultant' },
    { label: 'Hotel manager' },
    { label: 'Housing adviser' },
    { label: 'Human resources officer' },
    { label: 'Hydrologist' },
    { label: 'Illustrator' },
    { label: 'Immigration officer' },
    { label: 'Immunologist' },
    { label: 'Industrial/product designer' },
    { label: 'Information scientist' },
    { label: 'Information systems manager' },
    { label: 'Information technology/software trainers' },
    { label: 'Insurance broker' },
    { label: 'Insurance claims inspector' },
    { label: 'Insurance risk surveyor' },
    { label: 'Insurance underwriter' },
    { label: 'Interpreter' },
    { label: 'Investment analyst' },
    { label: 'Investment banker - corporate finance' },
    { label: 'Investment banker – operations' },
    { label: 'Investment fund manager' },
    { label: 'IT consultant' },
    { label: 'IT support analyst' },
    { label: 'Journalist' },
    { label: 'Laboratory technician' },
    { label: 'Land-based engineer' },
    { label: 'Landscape architect' },
    { label: 'Learning disability nurse' },
    { label: 'Learning mentor' },
    { label: 'Lecturer (adult education)' },
    { label: 'Lecturer (further education)' },
    { label: 'Lecturer (higher education)' },
    { label: 'Legal executive' },
    { label: 'Leisure centre manager' },
    { label: 'Licensed conveyancer' },
    { label: 'Local government administrator' },
    { label: 'Local government lawyer' },
    { label: 'Logistics/distribution manager' },
    { label: 'Magazine features editor' },
    { label: 'Magazine journalist' },
    { label: 'Maintenance engineer' },
    { label: 'Management accountant' },
    { label: 'Manufacturing engineer' },
    { label: 'Manufacturing machine operator' },
    { label: 'Manufacturing toolmaker' },
    { label: 'Marine scientist' },
    { label: 'Market research analyst' },
    { label: 'Market research executive' },
    { label: 'Marketing account manager' },
    { label: 'Marketing assistant' },
    { label: 'Marketing executive' },
    { label: 'Marketing manager (social media)' },
    { label: 'Materials engineer' },
    { label: 'Materials specialist' },
    { label: 'Mechanical engineer' },
    { label: 'Media analyst' },
    { label: 'Media buyer' },
    { label: 'Media planner' },
    { label: 'Medical physicist' },
    { label: 'Medical representative' },
    { label: 'Mental health nurse' },
    { label: 'Metallurgist' },
    { label: 'Meteorologist' },
    { label: 'Microbiologist' },
    { label: 'Midwife' },
    { label: 'Mining engineer' },
    { label: 'Mobile developer' },
    { label: 'Multimedia programmer' },
    { label: 'Multimedia specialists' },
    { label: 'Museum education officer' },
    { label: 'Museum/gallery exhibition officer' },
    { label: 'Music therapist' },
    { label: 'Nanoscientist' },
    { label: 'Nature conservation officer' },
    { label: 'Naval architect' },
    { label: 'Network administrator' },
    { label: 'Nurse' },
    { label: 'Nutritional therapist' },
    { label: 'Nutritionist' },
    { label: 'Occupational therapist' },
    { label: 'Oceanographer' },
    { label: 'Office manager' },
    { label: 'Operational researcher' },
    { label: 'Orthoptist' },
    { label: 'Outdoor pursuits manager' },
    { label: 'Packaging technologist' },
    { label: 'Paediatric nurse' },
    { label: 'Paramedic' },
    { label: 'Patent attorney' },
    { label: 'Patent examiner' },
    { label: 'Pension scheme manager' },
    { label: 'Personal assistant' },
    { label: 'Petroleum engineer' },
    { label: 'Pharmacist' },
    { label: 'Pharmacologist' },
    { label: 'Pharmacovigilance officer' },
    { label: 'Photographer' },
    { label: 'Physiotherapist' },
    { label: 'Picture researcher' },
    { label: 'Planning and development surveyor' },
    { label: 'Planning technician' },
    { label: 'Plant breeder' },
    { label: 'Police officer' },
    { label: 'Political party agent' },
    { label: 'Political party research officer' },
    { label: 'Practice nurse' },
    { label: 'Press photographer' },
    { label: 'Press sub-editor' },
    { label: 'Prison officer' },
    { label: 'Private music teacher' },
    { label: 'Probation officer' },
    { label: 'Product development scientist' },
    { label: 'Production manager' },
    { label: 'Programme researcher' },
    { label: 'Project manager' },
    { label: 'Psychologist (clinical)' },
    { label: 'Psychologist (educational)' },
    { label: 'Psychotherapist' },
    { label: 'Public affairs consultant (lobbyist)' },
    { label: 'Public affairs consultant (research)' },
    { label: 'Public house manager' },
    { label: 'Public librarian' },
    { label: 'Public relations (PR) officer' },
    { label: 'QA analyst' },
    { label: 'Quality assurance manager' },
    { label: 'Quantity surveyor' },
    { label: 'Records manager' },
    { label: 'Recruitment consultant' },
    { label: 'Recycling officer' },
    { label: 'Regulatory affairs officer' },
    { label: 'Research chemist' },
    { label: 'Research scientist' },
    { label: 'Restaurant manager' },
    { label: 'Retail banker' },
    { label: 'Retail buyer' },
    { label: 'Retail manager' },
    { label: 'Retail merchandiser' },
    { label: 'Retail pharmacist' },
    { label: 'Sales executive' },
    { label: 'Sales manager' },
    { label: 'Scene of crime officer' },
    { label: 'Secretary' },
    { label: 'Seismic interpreter' },
    { label: 'Site engineer' },
    { label: 'Site manager' },
    { label: 'Social researcher' },
    { label: 'Social worker' },
    { label: 'Software developer' },
    { label: 'Soil scientist' },
    { label: 'Solicitor' },
    { label: 'Speech and language therapist' },
    { label: 'Sports coach' },
    { label: 'Sports development officer' },
    { label: 'Sports therapist' },
    { label: 'Statistician' },
    { label: 'Stockbroker' },
    { label: 'Structural engineer' },
    { label: 'Systems analyst' },
    { label: 'Systems developer' },
    { label: 'Tax inspector' },
    { label: 'Teacher (nursery/early years)' },
    { label: 'Teacher (primary)' },
    { label: 'Teacher (secondary)' },
    { label: 'Teacher (special educational needs)' },
    { label: 'Teaching/classroom assistant' },
    { label: 'Technical author' },
    { label: 'Technical sales engineer' },
    { label: 'TEFL/TESL teacher' },
    { label: 'Television production assistant' },
    { label: 'Test automation developer' },
    { label: 'Tour operator' },
    { label: 'Tourism officer' },
    { label: 'Tourist information manager' },
    { label: 'Town and country planner' },
    { label: 'Toxicologist' },
    { label: 'Trade union research officer' },
    { label: 'Trader' },
    { label: 'Trading standards officer' },
    { label: 'Training and development officer' },
    { label: 'Translator' },
    { label: 'Transportation planner' },
    { label: 'Travel agent' },
    { label: 'TV/film/theatre set designer' },
    { label: 'UX designer' },
    { label: 'Validation engineer' },
    { label: 'Veterinary nurse' },
    { label: 'Veterinary surgeon' },
    { label: 'Video game designer' },
    { label: 'Video game developer' },
    { label: 'Volunteer work organiser' },
    { label: 'Warehouse manager' },
    { label: 'Waste disposal officer' },
    { label: 'Water conservation officer' },
    { label: 'Water engineer' },
    { label: 'Web designer' },
    { label: 'Web developer' },
    { label: 'Welfare rights adviser' },
    { label: 'Writer' },
    { label: 'Youth worker' },
];